### ISSUE TITLE
Error while running the script: unconverted data remains: 3

### ISSUE THREAD

**Issue by RestOp** [lolouk44/hassio-addons#11]
Hello,

Thanks for good job!

**Select Add-On (place a lowercase `x` for the relevant add-on)**
- Xiaomi Mi Scale https://github.com/lolouk44/hassio-addons/tree/master/mi-scale

**Describe the bug**
I have a errors in log
![image](https://user-images.githubusercontent.com/46259141/88597533-aa901680-d067-11ea-9c9d-161bed5b629e.png)
and it do not work.

Once it seems that has read my last measuremt under the name of Jo, when i have not corrected my config
![image](https://user-images.githubusercontent.com/46259141/88597748-35711100-d068-11ea-9ff1-1fba6e24244e.png)
But then, do not work.

**Scale (please complete the following information):**
 - Mi Body Composition Scale | XMTZC02HM

**Device running Home Assistant (please complete the following information):**
 - Actual Home Assistant with Supervisor
 - Device used to run the Script/Container Rrpi4 Docker 
 - Bluetooth device used: Built-in

Thanks a lot!

**Comment by RestOp** [comment]
I had a mistake in config. All works fine!
Thanks a lot!!!

**Comment by lolouk44** [comment]
Thanks. Out of interest could you confirm what tout dis wrong? If I can better catch this error I can give a more useful message

**Comment by RestOp** [comment]
Everything is perfect!
I have forgot Backquote in config.
Thanks a lot!
