### ISSUE TITLE
Great Job,  add-on work flawlessly!

### ISSUE THREAD

**Issue by fbpinheiro** [lolouk44/hassio-addons#12]
Do you do you could add-on for mikettle YM-K1501, for yeelight YLFW01YL, for amazfit BIP, Amazfit Verge and vaccum SDJQR02RR?

**Comment by lolouk44** [comment]
Sorry I doubt it. I don't have any of these products so no idea how they work and how they would communicate. I'm sure however that I've seen some of these online / on github. They would be under separate repos though... Happy hunting.
