### ISSUE TITLE
Possibility to import old history stored in the scale.

### ISSUE THREAD

**Issue by Fenixin** [lolouk44/hassio-addons#15]
First, thanks very much for your add-on, it works wonders! Now to the template:

**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Is your feature request related to a problem? Please describe.**
Not really a problem. The other day a read that the Xiaomi Mi Body Composition Scale, stored all the measurements made inside the scale. I was able to check this by using the app Open Scale. It downloaded months worth of measurements.

**Describe the solution you'd like**
It would be great being able to download all this data and include it in home assistant so I don't have to check old data in the xiaomi app. 

**Describe alternatives you've considered**
Maybe just a way to upload this information as CSV or somethingn like that, there are ways to download the old values as CSVs.

**Additional context**
Using HA 114.4 with xiaomi mi scale 0.1.7 in a Pi4, everything working like a charm. Also, I don't know if there is another way of doing that, I just thought that it would be a nice feature.

**Comment by lolouk44** [comment]
Thanks,

I wouldn't know where to start with this I'm afraid and probably mean a complete rewrite of the code as it's a different way to communicate with the scale.
Silly question though: If you're able to perform this with another app, why do you need me to build this too?
In addition I'm not sure getting the data into home assistant would be the best way as there is a high chance the data will be lost /wiped at some point. I personally use influxDB to store states & values  for long term and I use grafana to visualise. It may be easier to set this up and manually perform an import into influxDB?
Check this post to get you started:
https://community.home-assistant.io/t/complete-guide-on-setting-up-grafana-influxdb-with-home-assistant-using-official-docker-images/42860

**Comment by Fenixin** [comment]
Don't take it wrong, I didn't really know if doing it was easy or hard (a rewrite is hard so probably hard), I simply thought that it would be convinient. 

InfluxDB and grafana are already installed in the system but I never thought of importing the data manually. Thanks for the suggestion. I will try to do that. I have no idea how to proceed but I'm sure google will help.

Feel free to close the issue if you feel that it's not relevant to the add-on.

**Comment by lolouk44** [comment]
Oh I wasn't taking it wrong, don't worry 😉 
I just wanted to explain why I was probably not going to do it.
Glad I could help in the end.
For the import, have a look a this which might help: https://www.influxdata.com/blog/how-to-write-points-from-csv-to-influxdb/
Closing this now
