### ISSUE TITLE
is there any possible use this for Home Assistant not HassIO?

### ISSUE THREAD

**Issue by 5high** [lolouk44/hassio-addons#19]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lolouk44** [comment]
Have a look at my other repo
https://github.com/lolouk44/xiaomi_mi_scale
