### ISSUE TITLE
unable to add to HACS

### ISSUE THREAD

**Issue by madirshah** [lolouk44/hassio-addons#21]
hi,
I am trying to add the repo to has but unfortunately I get this message! is their any work around?
gr. Madir
![Screenshot 2020-10-01 at 23 56 00](https://user-images.githubusercontent.com/60794930/94867698-04370780-0442-11eb-927b-551d44fa1f66.jpg)

**Comment by MaximSN** [comment]
Hi, add this repository on supervisor add-on store

**Comment by lolouk44** [comment]
As per @MaximSN this repo is not on HACS
Follow the installation instructions

**Comment by qqgg231** [comment]
@lolouk44 
is it possible to add it to HACS?
