### ISSUE TITLE
Unit of Measure in exported entity not correct

### ISSUE THREAD

**Issue by benquan** [lolouk44/hassio-addons#22]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [X] Xiaomi Mi Scale

**Describe the bug**
My scale is set to lbs. And the reading is properly done in lbs but the entity's unit_of_measurement is hardcoded to kg.

**To Reproduce**
Steps to reproduce the behaviour, including error message if any.
Set a scale to lbs and link to this plugin

**Expected behaviour**
Expected unit_of_measure to be lbs

**Screenshots**
<img width="963" alt="Screen Shot 2020-10-31 at 3 56 53 PM" src="https://user-images.githubusercontent.com/3030645/97790846-db657780-1b91-11eb-9485-b0a5450ec54b.png">

**Scale (please complete the following information):**
My Body Composition Scale
Firmware: 0.3.2

**Device running Home Assistant (please complete the following information):**
Rapsberri Pi 4 (built in bluetooth)

**Additional context**

This is where kg gets hardcoded...

```
def discovery():
    for MQTTUser in (USER1_NAME,USER2_NAME,USER3_NAME):
        message = '{"name": "' + MQTTUser + ' Weight",'
        message+= '"state_topic": "miscale/' + MQTTUser + '/weight","value_template": "{{ value_json.weight }}","unit_of_measurement": "kg",'
        message+= '"json_attributes_topic": "miscale/' + MQTTUser + '/weight","icon": "mdi:scale-bathroom"}'
        publish.single(
                        MQTT_DISCOVERY_PREFIX + '/sensor/' + MQTT_PREFIX + '/' + MQTTUser + '/config',
                        message,
                        retain=True,
                        hostname=MQTT_HOST,
                        port=MQTT_PORT,
                        auth={'username':MQTT_USERNAME, 'password':MQTT_PASSWORD}
```

**Comment by lolouk44** [comment]
Can you confirm which version you're using? This was solved in 0.1.8
Latest version is 0.1.10

**Comment by benquan** [comment]
Using 0.1.10

**Comment by lolouk44** [comment]
sorry I get it now. It's an issue in the discovery indeed, however you do have the `weight_unit` attribute which is the correct one.
Unfortunately it is not possible to template a unit of measurement in HA so it's not _that_ relevant anyway
This is a minor aesthetic change so I probably won't create a new version just for this...
