### ISSUE TITLE
New version is broken

### ISSUE THREAD

**Issue by fufar** [lolouk44/hassio-addons#23]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x ] Xiaomi Mi Scale

**Describe the bug**

Does not start, in log:

[FATAL tini (6)] exec /entrypoint.sh failed: Permission denied

**Comment by lolouk44** [comment]
Thanks. Had to split docker container from non add-on image in view of making changes to allow unlimited users in a future version. Forgot that when you copy files under Windows the executable "rights" aren't copied over as well.
Fixed in [0.1.13](https://github.com/lolouk44/hassio-addons/releases/tag/0.1.13).
Images are currently being built and will be pushed shortly, but there is now a limitation of 200 pulls / 6h on docker :(
Looks like I may need to pay for subscriptions to remove this and may need to start asking for donations which I don't like :(

**Comment by kpcz** [comment]
updated to 0.1.13 but still
[FATAL tini (7)] exec /entrypoint.sh failed: Permission denied

Addon reinstall also did not help.

**Comment by lolouk44** [comment]
I had a similar report from another user. I made another fix and published [0.1.14](https://github.com/lolouk44/hassio-addons/releases/tag/0.1.14).
Reload your add-on data in the supervisor and update. Tested as working on my test Pi.

**Comment by fufar** [comment]
ok, 0.1.14 fixed permission error, but i have a new one :)
when i weight:
i get in log 
```
-------------------------------------
2020-11-25 14:59:18 - Starting Xiaomi mi Scale...
2020-11-25 14:59:18 - Loading Config From Add-On Options...
2020-11-25 14:59:18 - Config Loaded...
2020-11-25 14:59:18 - Discovery Completed...
2020-11-25 15:10:59 - Publishing data to topic miscale/Ilya/weight: {"weight":103.90,"weight_unit":"kg","bmi":33.93,"basal_metabolism":2028.22,"visceral_fat":26.74,"timestamp":"2020-11-25 15:10:59.084743"}
2020-11-25 15:10:59 - Data Published ...
```
i see new info in mqtt explorer (look at time)
![image](https://user-images.githubusercontent.com/22238388/100226264-89193b80-2f30-11eb-9553-389d9fdd24c8.png)

but in ha sensors are empty

![image](https://user-images.githubusercontent.com/22238388/100226317-9f26fc00-2f30-11eb-9f41-e1a428400fab.png)

**Comment by lolouk44** [comment]
@fufar can you share the HA config related to the sensor pls?

**Comment by fufar** [comment]
```
- platform: mqtt
  name: "Илья Вес"
  state_topic: "miscale/Ilya/weight"
  value_template: "{{ value_json['weight'] }}"
  unit_of_measurement: "kg"
  json_attributes_topic: "miscale/Ilya/weight"
  icon: mdi:scale-bathroom
```

**Comment by lolouk44** [comment]
Sorry mate I can't see what's not working. 
Clearly the message is sent to MQTT, All I can think of is a connection issue between HA and MQTT?
Anything in the logs? Have you tried to restart HA?
Not sure what else to try to be honest

**Comment by fufar** [comment]
maybe something with mosquitto broker <-> ha, but all other devices works(zigbee mostly)
see this errors in log
![image](https://user-images.githubusercontent.com/22238388/100231828-989c8280-2f38-11eb-94cd-0dfdb42617cb.png)

**Comment by lolouk44** [comment]
This is a different issue. Do you mind opening a new one please to track it separately?
Also please confirm in the new issue whether you're using MQTT Discovery.
