### ISSUE TITLE
[FATAL tini (7)] exec /entrypoint.sh failed: Permission denied

### ISSUE THREAD

**Issue by kamilsulek** [lolouk44/hassio-addons#24]
After update new version 0.1.13 on HASSIO addon not working. I have message in log:

[FATAL tini (7)] exec /entrypoint.sh failed: Permission denied

I don't use docker.

**Comment by lolouk44** [comment]
Hi @kamilsulek 
Duplicate of https://github.com/lolouk44/hassio-addons/issues/23
Fixed in 0.1.14
