### ISSUE TITLE
Zero weight sensor in HA

### ISSUE THREAD

**Issue by fufar** [lolouk44/hassio-addons#25]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- Mi Smart Scale 2           

**Describe the bug**
i get in log
```

-------------------------------------
2020-11-25 14:59:18 - Starting Xiaomi mi Scale...
2020-11-25 14:59:18 - Loading Config From Add-On Options...
2020-11-25 14:59:18 - Config Loaded...
2020-11-25 14:59:18 - Discovery Completed...
2020-11-25 15:10:59 - Publishing data to topic miscale/Ilya/weight: {"weight":103.90,"weight_unit":"kg","bmi":33.93,"basal_metabolism":2028.22,"visceral_fat":26.74,"timestamp":"2020-11-25 15:10:59.084743"}
2020-11-25 15:10:59 - Data Published ...
```
i see new info in mqtt explorer
![image](https://user-images.githubusercontent.com/22238388/100239853-f3d37280-2f42-11eb-89c2-e0bc261308f2.png)

but in ha sensors are empty
![image](https://user-images.githubusercontent.com/22238388/100239869-f635cc80-2f42-11eb-8b12-c0bedc7b2b7b.png)

**Device running Home Assistant (please complete the following information):**
 - Device used to run the Script/Container [e.g. Raspberry Pi, NUC] Synology nas + docker ha
 - Bluetooth device used [e.g. Built-in, USB Dongle] USB Dongle

**Additional context**
HA 0.118.3
MQTT Discovery is enabled
Mosquitto broker 5.1

**Comment by lolouk44** [comment]
Hi @fufar 
Looking into this for you, what do you click on to get the chart in the above screenshot?
What's odd is that your sensor definition shows `name: "Илья Вес"` yet the above screenshot shows a name of `ilya weight`
If you click on the cogwheel on your chart, what is the name of the sensor?

**Comment by lolouk44** [comment]
Not sure if related but there was an issue with the MQTT Discovery. I just pushed [0.1.15](https://github.com/lolouk44/hassio-addons/releases/tag/0.1.15)
Can you try to update and let me know if the issue is still here?

**Comment by fufar** [comment]
0.1.16 working again, thx
all sensors have 2 copies now, but i can live with it 👍
![image](https://user-images.githubusercontent.com/22238388/100351804-14600300-2ffd-11eb-9648-76bcc823532e.png)
