### ISSUE TITLE
Addon not starting up! 

### ISSUE THREAD

**Issue by CollaVinilica** [lolouk44/hassio-addons#27]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [ ] Xiaomi Mi Scale

**Describe the bug**
Addon not starting, with the error 

 ```
 File "/opt/miscale/Xiaomi_Scale.py", line 196
    message+= '"state_topic": "' + MQTT_PREFIX + '/' + MQTTUser + '/weight","value_template": "{{ value_json['weight'] }}",'
                                                                                                              ^
SyntaxError: invalid syntax

```
**To Reproduce**

After updating the configuration file, that error is all I get

**Scale (please complete the following information):**
 - Xiaomi Mi Scale Body Composition 2

**Device running Home Assistant (please complete the following information):**
 - HassOS

**Comment by lolouk44** [comment]
Thanks. I just pushed [0.1.16](https://github.com/lolouk44/hassio-addons/releases/tag/0.1.16) which should fix it. Give it a few minutes for the image to be available on Docker

**Comment by CollaVinilica** [comment]
> Thanks. I just pushed [0.1.16](https://github.com/lolouk44/hassio-addons/releases/tag/0.1.16) which should fix it. Give it a few minutes for the image to be available on Docker

New version installed, same error

**Comment by lolouk44** [comment]
That's odd. It's definitely working for me.
Can you try and uninstall / reinstall pls?

**Comment by CollaVinilica** [comment]
Installed on a testing setup with an old Pi 3 and it works great! Thanks a lot!
