### ISSUE TITLE
Configuration env. variables can't be comment out or deleted - No MQTT default connection possible

### ISSUE THREAD

**Issue by andigehle** [lolouk44/hassio-addons#28]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x ] Xiaomi Mi Scale

**Describe the bug**
As the Add-On installation guide describes, not required configuration environment variables should be comment out. E.g. "MQTT_USERNAME: user", "MQTT_PASSWORD: passwd" (when using default/not auth. mqtt broker on HA) or the "USER3_[....]" variables when only running a 2-Person-Configuration. In the current Add-On version commenting out such env. lines and saving these changes with the HA GUI under "Supervisor > Xiaomi Mi Scale > Configuration" will recreate the lines instead of accepting comment out/deleted values.
This leads to connection faults when using the default settings for HA MQTT broker without user and pass.

**To Reproduce**
1. Open "Configuration" tab in HA "Supervisor > Xiaomi Mi Scale > Configuration"
2. a. Change line "MQTT_USERNAME: user" to "#MQTT_USERNAME: user"
2. b. Or delete the line "MQTT_USERNAME: user"
3. Save the changes (Restarting the Add-On doesn't matter)
4. Switch to tab "Info" (Or an other view - We want to reload the "Configuration" tab)
5. Switch back to tab "Configuration" ("Supervisor > Xiaomi Mi Scale > Configuration")
6. a. See the comment out line is fallen back to "MQTT_USERNAME: user"
6. b. See the deleted line is fallen back to and added "MQTT_USERNAME: user"

MQTT Log:
```
1606558445: New connection from x.x.x.x on port 1883.
[ERROR] Auth error with user
1606558446: Socket error on client <unknown>, disconnecting.
```

**Additional Context**
- Changing env. variables without deleting or commenting out is working and also persistent when reloading the "Configuration" tab.
- Besides deleting or commenting out - As workaround inserting null-values (like ~, null, false, '', 0) results in errors thrown by the configuration parser. `Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'HCI_DEV': 'hci0', 'MISCALE_MAC': ...}`
- ~~Same bug occurs when editing the configurations directly by ` sudo vi /usr/share/hassio/addons/data/79ff755f_xiaomi_mi_scale/options.json`. After restarting the addon, the variables are added back again with the default values in options.json~~ Any direct changes in the volume's options.json are synced back by Hassio after addon restart? 

**Device running Home Assistant (please complete the following information):**
System Health

Home Assistant Core Integration
version: 0.118.4
installation_type: Home Assistant Supervised
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.4.77-v7l+
arch: armv7l

Hass.io
host_os: Raspbian GNU/Linux 10 (buster)
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.13
installed_addons: Xiaomi Mi Scale (0.1.16), Mosquitto broker (5.1)

**Comment by andigehle** [comment]
Setting up this project without Supervisor in Docker and leaving out these env. variables worked fine. But as Add-On via HA Supervisor ... it seems that it's not possible to configure to **not** use an user and password for mqtt. So maybe it has to do with the HA Add-On `config.json` or/and how it is used?
In general, isn't it problematic to define example data as defaults for optional **null-able** configurations? For default options like `"HCI_DEV": "hci0"` with schema `"HCI_DEV": "str?"`  this might be okay, because this data is needed in any way(?) and is provided by either the user or else the default value. But for `"MQTT_PASSWORD": "passwd"` with schema `"MQTT_PASSWORD": "str?"` - Will this not lead to use the default password "passwd" when the user hasn't set one?

**Comment by lolouk44** [comment]
Thanks for your comments.
I've followed doc [here](https://developers.home-assistant.io/docs/add-ons/configuration#options--schema)
Admittedly I don't have any MQTT broker set up without username or password so haven't specifically tested this.
I can see the the credentials come back when deleting them, even though they're set as optional.
I'll have to seek help from the community...

**Comment by andigehle** [comment]
I think the option/schema `"not_need": "str?"` in the docs is the right example for this use case ("not required/ default null"-value). See "not_need" is not listed in `options` but only in the `schema`-part. I am no HA-Add-On developer, but as i understand it: If the user doesn't provide the `not_need` value, then `not_need` is simply `null` (because there is no default value in `options` defined). 

If you want I can try to write a Pull-Request, but it should be simple deleting all the default-(example)-values in the `options` (config.json), which should be null as default, but letting stay the `schema`-part as it is. The documentation should then be changed to "add these lines like USER_3 Missy if you want ..." instead of "comment out the lines ... if you want ..."

**Comment by lolouk44** [comment]
Thanks for your feedback. There is something else.

If you look at example config from [zigbee2mqtt](https://github.com/danielwelch/hassio-zigbee2mqtt/blob/master/zigbee2mqtt/config.json) you will see that the UN and PW are listed and put as optional (with the extra "?" in the schema)
so not sure why it fails with my add-on

Had a quick look at the community but couldn't find anything obvious (plus I'm at work right now so can only look at this during my breaks)

Thanks for the offer of a PR, but if I simply remove the UN and PW from the template, I'll have users complaining (rightly so) that they don't know where to enter that data and how to call it (how would a user know the variable name is `username` and not `user_name` for example).
Also you cannot comment lines in a json file, it's different than yaml, so I can't list these options commented in either...

**Comment by andigehle** [comment]
Yeah, there is something else. Tested zigbee2mqtt Add-On and deleted 
```
mqtt:
  user: my_user
  password: my_password
```
It's not re-added.

**Comment by lolouk44** [comment]
trying to look at something else that would simplify config: 
https://developers.home-assistant.io/docs/add-ons/communication/#services-api
Bear with me pls

**Comment by andigehle** [comment]
I compared further with the `zigbee2mqtt` Add-On and deleted all entries in the configuration tab to see which options are re-added, wich not, and if I can find a pattern. No matter schema (int? or int or str? or str or ...), the complete default set is just re-added - With the only exception mqtt.user and mqtt.password .... I am currently not seeing why. Also searched a bit in their repository and found a [pull-request](https://github.com/danielwelch/hassio-zigbee2mqtt/pull/443) - which is quite funny - because it stages to "Changed mqtt.server, mqtt.user, mqtt.password to be optional". [That pull-request wants to remove the default-options](https://github.com/danielwelch/hassio-zigbee2mqtt/pull/443/commits/77a30134bb1c1470d25fa07975ad4f10aa62732a#diff-ee3847d65462928a87198e94cbd87fa8326073c1bc3efffa8a8f0076c8332341L37-L40) as we thought first. I currently can only guess wildly ... Maybe it's a global HA issue or handling for credentials in config files?

**Comment by andigehle** [comment]
I have another guess. Maybe it has something to do with nesting/inner options. I haven't set up an development env. and can't test it, but what if the options for user and pass are nested like they are in the Zigbee2mqtt example?

**Comment by somebox** [comment]
I ran into this problem as well. The solution for me: 
1) I was missing `customize: !include customize.yaml` in my configuration.yaml - this apparently causes some things not to save correctly. 
2) I created a home assistant user for mqtt. To do this, I had to enable the "advanced" setting in my profile. Then I added a new user and password for use with MQTT. MQTT will by default will allow any HA user to access it. Then, I added this username and password into the Xiaomi Scale addon, and it saved properly. After restarting HA core, and the addon, things started working.
I suspect that issue 1) was maybe not related, but including it here in case.

**Comment by lolouk44** [comment]
I have sorted some things on the main scale code (the non add-on one) so can look at this issue in the next few days
I can try and move the MQTT credentials into an array (nested) and see if that works better.

**Comment by lolouk44** [comment]
I've rewritten the config into a json file.
does that work for you now?

**Comment by lolouk44** [comment]
Closing stale issue
