### ISSUE TITLE
Bug with connection 

### ISSUE THREAD

**Issue by ozzinse** [lolouk44/hassio-addons#29]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [ x] Xiaomi Mi Scale

**Describe the bug**
Bluetooth connection error: Failed to execute management command 'scanend' (code: 13, error: Invalid Parameters)

**To Reproduce**
Not possible

**Expected behaviour**
Get all data from Mi scale

**Screenshots**
no

**Scale (please complete the following information):**
 - Name Mi scale
 - Model 2

**Device running Home Assistant (please complete the following information):**
 - NUC
 - USB Dongle

**Additional context**

**Comment by lolouk44** [comment]
Thanks for your feedback.
This is an issue with bluepy I'm afraid, there are a few issues raised on its GitHub with a few things to try:
https://github.com/IanHarvey/bluepy/issues/150
https://github.com/IanHarvey/bluepy/issues/218
