### ISSUE TITLE
Non-HASSIO usage instructions / release artifact 

### ISSUE THREAD

**Issue by saikek** [lolouk44/hassio-addons#30]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [X] Xiaomi Mi Scale 2

**Is your feature request related to a problem? Please describe.**
I'm using python-based HA. I'm not sure how to use your addon - i've extracted repo into `custom_components` and changed configuration - but HA sensors are not updated and there is nothing in MQTT.

**Describe the solution you'd like**
Please do actions release or graft some instruction on how to use with HA.

**Describe alternatives you've considered**
None at the moment.

**Additional context**

**Comment by saikek** [comment]
Also HA version `0.118.4`, 
I've updated MAC, and all config params.
Other modules from `custom_components` are working.

**Comment by lolouk44** [comment]
This repo is only for the home assistant version, aka hass.io, not for the core version.
Use this version instead 
https://github.com/lolouk44/xiaomi_mi_scale
