### ISSUE TITLE
Supervisor Log warning

### ISSUE THREAD

**Issue by DarKOrange75** [lolouk44/hassio-addons#32]
**Describe the bug**
Warning in supervisor log:

21-02-10 08:20:41 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Xiaomi Mi Scale
21-02-10 08:20:41 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Xiaomi Mi Scale
21-02-10 08:20:41 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Dropbox Sync
21-02-10 08:20:42 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Xiaomi Mi Scale

**Desktop/Server (please complete the following information):**
HomeAssistant core-2021.2.2
supervisor-2021.02.6

**Comment by lolouk44** [comment]
Thanks.
Transferred issue to the add-on repo.
I'll look into this once I've fixed my RPi3.

**Comment by lolouk44** [comment]
Looking into this. I can see the `startup` option in the config.json and fixed it in the next version, but I cannot see the `devices` one?

**Comment by lolouk44** [comment]
Fixed in [0.1.17](https://github.com/lolouk44/hassio-addons/releases/tag/0.1.17)

**Comment by DarKOrange75** [comment]
Thank you for being so fast!
