### ISSUE TITLE
Bad names for MQTT variables.

### ISSUE THREAD

**Issue by zerofull56** [lolouk44/hassio-addons#33]
Will need to change variable names otherwise Home Assistant does not write data to them.
Basal Metabolism -> Basal_Metabolism
Visceral_Fat -> Visceral_Fat

**Comment by lolouk44** [comment]
I'm confused. Home assistant should not write back to MQTT, it should only get the information from MQTT to then display as a sensor.

**Comment by zerofull56** [comment]
Sorry, this is my mistake... It's work perfectly, thanks.

**Comment by lolouk44** [comment]
Thanks. That said It would make sense to follow json standards of snake case, so will look at this in a future release.
