### ISSUE TITLE
Bluetooth connection error: Failed to execute management command 'scanend' (code: 11, error: Rejected)

### ISSUE THREAD

**Issue by magiva** [lolouk44/hassio-addons#34]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [ ] Xiaomi Mi Scale

**Describe the bug**
the log shows this most times
Bluetooth connection error: Failed to execute management command 'scanend' (code: 11, error: Rejected)
the odd occasion it downloads data (1 out of 5)

**To Reproduce**
let the add on do its thing

**Expected behaviour**
sync data

**Screenshots**
![image](https://user-images.githubusercontent.com/7522405/110101399-c436d080-7da3-11eb-8579-a45ea166692e.png)

**Scale (please complete the following information):**
Mi Body Composition Scale 2 | XMTZC05HM

**Device running Home Assistant (please complete the following information):**
Raspberry pi 3 with built in Bluetooth

**Additional context**

**Comment by lolouk44** [comment]
Can you confirm which setting you have for `BLUEPY_PASSIVE_SCAN`?
Have you tried to change it to `true`?
Also can you confirm that the bluetooth radio is turned on?

**Comment by magiva** [comment]
i set the passive to false.
i did try it with true but the log never updates past 'discovery completed'
i see in the code that hci is cycled down to up, i tried that in ssh
outside of the docker to see if that helped but it didnt
[image: image.png]

**Comment by magiva** [comment]
i can see in lsusb that bluetooth is turned on and it did get 1 piece of data but then never again.
bluetooth is also used for user proximity so i know its on

**Comment by lolouk44** [comment]
> i did try it with true but the log never updates past 'discovery completed'

That sounds more promising, i.e. no error messages.
Have you tried to step on the scale then?
The scale will only communicate for about 10-15 min before going to sleep and then you won't get any results anymore...

**Comment by magiva** [comment]
interesting, i did try this after setting it to passive yesterday but got
nothing then and just now i got

2021-03-06 15:12:19 - Starting Xiaomi mi Scale...
2021-03-06 15:12:19 - Loading Config From Add-On Options...
2021-03-06 15:12:19 - Config Loaded...
2021-03-06 15:12:21 - Discovery Completed...
2021-03-06 15:15:51 - Publishing data to topic miscale/Mark/weight:
{"weight":81.00,"weight_unit":"kg","bmi":15.06,"basal_metabolism":1290.18,"visceral_fat":2.98,"lean_body_mass":62.73,"body_fat":11.95,"water":48.59,"bone_mass":3.16,"muscle_mass":78.77,"protein":16.00,"body_type":"Superhero","metabolic_age":24,"timestamp":"2021-03-06
15:15:51.825682"}
2021-03-06 15:15:51 - Data Published ...


So ill monitor it and see how it goes, maybe i get a usb bluetooth
instead of using the internal one

**Comment by lolouk44** [comment]
So it's working 😊
Closing the issue in that case
