### ISSUE TITLE
Config always uses kg even if display is in lbs

### ISSUE THREAD

**Issue by hkrob** [lolouk44/hassio-addons#36]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Describe the bug**
In the config, you always need to use KG even if the Display and MQTT output is in lbs
This isn't a big deal - but it isn't documented

**To Reproduce**
1. Set MiScale to lbs
2. Take Measurement

The MQTT output will be the following only if the config is set using KG
{"weight":171.50,"weight_unit":"lbs","bmi":24.55,"basal_metabolism":1527.84,"visceral_fat":14.65,"timestamp":"2021-05-06 10:19:52.539306"}

Config
  - NAME: Rob
    SEX: male
    GT: 70
    LT: 99
    HEIGHT: 178
    DOB: '19xx-xx-xx'

If the config is done using the values from lbs - no MQTT message will be output.

**Expected behaviour**
* Amend the documentation
* OR have the config apply regardless of KG or LBS

**Screenshots**
N/A

**Scale (please complete the following information):**
 - Name
 - Model XMTZC01HM

**Device running Home Assistant (please complete the following information):**
 - Odroid N2+
 - BT Dongle

**Additional context**
N/A

**Comment by lolouk44** [comment]
Thanks for this.
I see where the issue lies. Would you be free to run a test once I've amended the code?

**Comment by hkrob** [comment]
Sure thing, happy to test

**Comment by lolouk44** [comment]
Thanks. Can you test with v0.2.2b that I just published pls?
I'm pretty sure it'll work but just want confirmation before I publish the `:latest` tag

**Comment by hkrob** [comment]
Looking good with 0.2.4 !
Cheers!

**Comment by lolouk44** [comment]
Thanks for confirming
