### ISSUE TITLE
cant update or install anymore

### ISSUE THREAD

**Issue by magiva** [lolouk44/hassio-addons#38]
updating or removing then installing now gives this new error from latest version of hassio 2021.5.1

404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.2.2&fromImage=lolouk44%2Fxiaomi-mi-scale-ha-add-on: Not Found ("manifest for lolouk44/xiaomi-mi-scale-ha-add-on:0.2.2 not found: manifest unknown: manifest unknown")

it has internet, i can add the repo - i removed and re-added.
installed and removed a couple of others to see if they were ok, they were

Log:
21-05-10 12:20:31 INFO (SyncWorker_0) [supervisor.docker.interface] Updating image lolouk44/xiaomi-mi-scale-ha-add-on:0.2.0 to lolouk44/xiaomi-mi-scale-ha-add-on:0.2.2
21-05-10 12:20:31 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image lolouk44/xiaomi-mi-scale-ha-add-on with tag 0.2.2.
21-05-10 12:20:33 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install lolouk44/xiaomi-mi-scale-ha-add-on:0.2.2 -> 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.2.2&fromImage=lolouk44%2Fxiaomi-mi-scale-ha-add-on: Not Found ("manifest for lolouk44/xiaomi-mi-scale-ha-add-on:0.2.2 not found: manifest unknown: manifest unknown").

**Comment by lolouk44** [comment]
it looks as though Home Assistant does not support:
- pre-releases and treats them as regular releases
- letters appended at the end of a version for e.g. alpha/beta releases etc
so I'm publishing v0.2.3, should be ready in about 10 min
If you can confirm a close the ticket then?

**Comment by hkrob** [comment]
OK same here... HA is still showing the older version 0.2.2, will try 0.2.3 when the build is done

**Comment by magiva** [comment]
i can see that the latest release is 0.2.3 but hassio thinks its 0.2.2 and throws error into the log.
ive removed it, updated, added repo and then updated but i still get

21-05-10 12:43:01 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image lolouk44/xiaomi-mi-scale-ha-add-on with tag 0.2.2.
21-05-10 12:43:03 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install lolouk44/xiaomi-mi-scale-ha-add-on:0.2.2 -> 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.2.2&fromImage=lolouk44%2Fxiaomi-mi-scale-ha-add-on: Not Found ("manifest for lolouk44/xiaomi-mi-scale-ha-add-on:0.2.2 not found: manifest unknown: manifest unknown").

so maybe i leave it a while, maybe there are backend events to update meta before it all settles

**Comment by hkrob** [comment]
0.2.4 not working either

Failed to install add-on
404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.2.4&fromImage=lolouk44%2Fxiaomi-mi-scale-ha-add-on: Not Found ("manifest for lolouk44/xiaomi-mi-scale-ha-add-on:0.2.4 not found: manifest unknown: manifest unknown")

**Comment by lolouk44** [comment]
> so maybe i leave it a while, maybe there are backend events to update meta before it all settles

Nope, that normally happens when "one" pushes a new release but doesn't update the version on the various files (config, dockerfile,...) 🤦 
2.4 [being built](https://github.com/lolouk44/hassio-addons/actions/runs/828208730)...

**Comment by magiva** [comment]
all good now :)
