### ISSUE TITLE
Add repository.json

### ISSUE THREAD

**Issue by stefangries** [lolouk44/hassio-addons#4]
If you add a repository.json, it is very easy to install this addon for users. Then users only have to add a repository URL to their Home Assistant installation and can easily install and update the addon.

Developers guide can be found here:
https://developers.home-assistant.io/docs/add-ons/repository/

**Comment by lolouk44** [comment]
Thanks. Will look into it. Got loads on my plate now thanks to you 😄

**Comment by stefangries** [comment]
I hope it is okay if I keep on reporting bugs and submitting feature requests. I don't want to be unkind and make demands, but I want to help to improve / extend the software.

**Comment by lolouk44** [comment]
Please do keep them coming. I'm also trying to extend the software. As much as an amateur that I am, not everybody can produce the crappy code I "designed" 😜
Hopefully it gets better and more people can use it

**Comment by stefangries** [comment]
Then thank you very much for your work. I really appreciate it!

**Comment by remb0** [comment]
also I want to say thank you very much!  we really appreciate your work.

**Comment by lolouk44** [comment]
Added in upcoming 0.1.7

**Comment by fufar** [comment]
tryed to install this way, got an error
`20-07-06 14:31:15 INFO (SyncWorker_13) [supervisor.docker.interface] Pull image lolouk44/xiaomi-mi-scale tag 0.1.7.
20-07-06 14:31:16 ERROR (SyncWorker_13) [supervisor.docker.interface] Can't install lolouk44/xiaomi-mi-scale:0.1.7 -> 404 Client Error: Not Found ("manifest for lolouk44/xiaomi-mi-scale:0.1.7 not found").`

i think no tag 0.1.7 in docker hub, i see only 0.1.6 and latest tags

**Comment by lolouk44** [comment]
lol that's why I said "upcoming" :D
I'm still building the docker image...
Once done I'll update the release on the repo

**Comment by lolouk44** [comment]
oh I so much prefer bat timing than bad timing 🤣

**Comment by lolouk44** [comment]
Try now it should work
