### ISSUE TITLE
Can't find the add-on in the Add-on store.

### ISSUE THREAD

**Issue by Gregerwhut** [lolouk44/hassio-addons#40]
I have problems finding the add-on in in the Add-on store. 

I have added 
"https://github.com/lolouk44/hassio-addons" 
to the repositories and restarted home assistant and than searched for Xiaomi Mi Scale in the add-on store without luck. 

BR.,

**Comment by lolouk44** [comment]
Please check the doc, I have written step by step instructions on how to
add the repo to then install the add on

**Comment by Gregerwhut** [comment]
Thanks for the reponse. It got me further but eventually not all the way. 
I get stuck at the HA setup with the
 "/USER_NAME/ " from  state_topic: "miscale/USER_NAME/weight"  in the weight example - should i change anything here? 
I have changed the miscale configuration, and it should be right.  

When I directly copy paste the weight example into my sensor block, restart HA, the " sensor.example_name_weight " does not seem to auto disover via the MQTT autodiscovery. I can see it in my DEV tools but it does not update.

**Comment by lolouk44** [comment]
Have you set up an mqtt broker in HA? You'll need that for the add on to work

**Comment by Gregerwhut** [comment]
Yes I have.

**Comment by lolouk44** [comment]
Have you tried an app like mqtt explorer to ensure the data is actually being sent to your MQTT Broker?

Can you weeight yourself then post:
- a copy of your config.json file please (Make sure you redact any credentials)
- your HA logs
- The add-on logs

**Comment by Gregerwhut** [comment]
I managed to get it working now. As i was about to send you the Logs, i noticed that the add-on for some reason where not started. Thanks for the help and add-on
