### ISSUE TITLE
ESP32 board with OpenMQTTGateway

### ISSUE THREAD

**Issue by pedroct** [lolouk44/hassio-addons#42]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Is your feature request related to a problem? Please describe.**
I have an ESP32 board with OpenMQTTGateway configured and working correctly. I would like to know if it is possible not to use HCI_DEV, but ESP32 with its add-on.

**Describe the solution you'd like**
Have another version of the add-on for use with an ESP32 board and OpenMQTTGateway. I have a scale topic at OpenMQTTGateway: home/OpenMQTTGateway_ESP32_BLE/BTtoMQTT/5CCRD372A23R.

**Describe alternatives you've considered**

**Additional context**

**Comment by lolouk44** [comment]
You must have me confused with a different repo. This report is only for computers / Raspberry Pi style computers, I haven't written any code for development boards like the ESP32/8266
