### ISSUE TITLE
problem while upgrading 0.2.4 -> 0.2.5 and while installing 0.2.5 alone

### ISSUE THREAD

**Issue by pejotigrek** [lolouk44/hassio-addons#44]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Describe the bug**
I use Home Assistant supervised, saw today that there's an updatefor Xiaomi Mi Scale add-on from 0.2.4 to 0.2.5. tried to upgrade and this error occurs:

```
Can't install lolouk44/xiaomi-mi-scale-ha-add-on:0.2.5: 404 Client Error for
http+docker://localhost/v1.41/images/create?tag=0.2.5&fromImage=lolouk44%2Fxiaomi-mi-scale-ha-add-on:
Not Found ("manifest for lolouk44/xiaomi-mi-scale-ha-add-on:0.2.5 not found: manifest unknown: manifest unknown")
```

then tried to uninstall 0.2.4 and make a clean install of 0.2.5 - the same error occurs.
tried to re-add repository and make a clean install - the same error occurs.

**To Reproduce**
1. click on "install" on 0.2.5 version or "update" on 0.2.4 version

**Expected behaviour**
correct update of the addon to latest version

**Screenshots**
![image](https://user-images.githubusercontent.com/10796588/123662305-9e8f7480-d835-11eb-898d-038fdac3933e.png)

**Scale (please complete the following information):**
 - Name Xiaomi Mi Body Composition Scale 2
 - Model # XMTZC02HM

**Device running Home Assistant (please complete the following information):**
 - HP t620 thinclient 
 - usb dongle

**Additional context**
n/a

**Comment by fufar** [comment]
same for me

**Comment by lolouk44** [comment]
This is an issue with the github workflow. I've just kick ran the jobs again, should hopefully be republished in about 10 min. If not I'll just deploy a new release again

**Comment by lolouk44** [comment]
re-running the jobs did not work so published 0.2.6.
Another ~10 to wait and should be fixed.

**Comment by lolouk44** [comment]
Can anyone confirm 0.2.6 is working pls so I can go and have my dinner? 😉

**Comment by pejotigrek** [comment]
it didn't showed up yet for me. but I'll let you know if it will :)

thank you for such a quick reaction!

enjoy your dinner :)

**Comment by pejotigrek** [comment]
0.2.6 showed up & updated without any problems! one more time thank you for lighning-fast fix! :)
