### ISSUE TITLE
Can I see history of measurements?

### ISSUE THREAD

**Issue by KBD77** [lolouk44/hassio-addons#48]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Is your feature request related to a problem? Please describe.**
I see only the last weight with all the attributes comparing with previous.

**Describe the solution you'd like**
How can I see my weight in longterm. Some chart or table

**Describe alternatives you've considered**

**Additional context**

**Comment by lolouk44** [comment]
You can see your weight for the past 24h by default, but for long term you'll currently need to store this in a third party database (I use Influxdb and Grafana) there is currently no device class for weight in HA therefore it's not compatible with the long term statistics feature released in 2021.8
