### ISSUE TITLE
Mqtt gets disconnected almost instantly after connected 

### ISSUE THREAD

**Issue by biejay** [lolouk44/hassio-addons#49]
When i startup the addon, it **successfully connects** to my mosquitto mqtt addon.
But i **disconnects again super fast**. I got data from my Mi scale on first setup a few times but without changing anything, it now does not work anymore. 
Is that a **known Bug or can i somehow fix that**?

Thanks in advance!

Mosquitto Log:
> 1630609524: New connection from 172.30.32.1 on port 1883.
> 1630609524: New client connected from 172.30.32.1 as auto-*********  (p2, c1, k60, u'mi****').
> 1630609524: Client auto-********* disconnected.

**Comment by lolouk44** [comment]
The client only connects to send data then disconnects. This is not a big is by design. The next time you weigh yourself it would connect and send the data then disconnect again... Just make sure your don't also have the Xiaomi app running, the scale only accepts one connection at a time
