### ISSUE TITLE
External bluetooth support

### ISSUE THREAD

**Issue by Korte68** [lolouk44/hassio-addons#52]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x ] Xiaomi Mi Scale

**Is your feature request related to a problem? Please describe.**
I use an ESP32 to read the data from the scale. It returns the weight, and the impedance as a sensor.
Is it possible to use this sensor data as an alternative source ? 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lolouk44** [comment]
Aside from pretty much rebuilding the add-on to cater for an external source (not even sure how I'd pull that data), I don't think it'll be possible.
It would probably be easier to edit the code on the ESP than rewriting this one.
Thanks for the suggestion though
