### ISSUE TITLE
 illegal discovery topic

### ISSUE THREAD

**Issue by TPochobradsky** [lolouk44/hassio-addons#53]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x ] Xiaomi Mi Scale

**Describe the bug**
I have use diacritic in configuration. Which lead to error. The error still persists although i have changed name from "Tomáš" to "Tomas" in configuration.
Where is possible to repair it?

Logger: homeassistant.components.mqtt.discovery
Source: components/mqtt/discovery.py:104
Integration: MQTT (documentation, issues)
First occurred: 14:22:33 (1 occurrences)
Last logged: 14:22:33

Received message on illegal discovery topic 'homeassistant/sensor/miscale/Tomáš/config'

**Comment by lolouk44** [comment]
Where is the error showing up? In HA or in the add-on logs?
If you have modified the config the discovery topic should have updated to include the new topic (though the old one would still show up)
Have you tried a tool like [MQTT Explorer](http://mqtt-explorer.com/) to browse the topics and delete the "offending" topic in the `homeassistant` topic?

**Comment by TPochobradsky** [comment]
I'm sorry, I don't want offending you. I don't know what to do and trying to find help. The error log is from HA, but I thought that you know where is possible to correct it.
I will try tried MQTT Explorer as you recomented. Thanks

**Comment by TPochobradsky** [comment]
Yes, I have deleted the old sensor and error is solved. Thank you very much for advice and work on integration.
