### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by SoulEater45** [lolouk44/hassio-addons#54]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Describe the bug**
Only a part of the data is transmitted to Home Assistant.

**To Reproduce**
I am not able to switch between transmitting all and the partial data, so I don't know what causes it.

**Expected behaviour**
The usual data is transmitted, which is also listed in the addon description.

**Screenshots**
```
Publishing data to topic miscale/Name/weight: 
```
```json
{
  "weight": 73.0,
  "weight_unit": "kg",
  "bmi": 22,
  "basal_metabolism": 1600.0,
  "visceral_fat": 8.0,
  "timestamp": "2021-12-03 00:00:00.0"
}
```
I edited the data a bit, but that's what is received.

**Scale (please complete the following information):**
 - Name Composition Scale 2
 - Model <not sure, but I will look it up later>

**Device running Home Assistant (please complete the following information):**
 - Device used to run the Script/Container: Raspberry Pi 4B
 - Bluetooth device used: Built-in

**Additional context**
-

**Comment by lolouk44** [comment]
Full data is published if the scale can measure your impedance.
To measure your impedance you need to step on the scale barefoot.

**Comment by SoulEater45** [comment]
Thanks for the fast feedback.
I got the issue with some data from my brother who uses the scale and I asked him if he used it barefoot, which he did. But he failed to mentioned that he didn't wait for the rest of the measurements to be taken, so yeah.
Thanks for clarification! :)
