### ISSUE TITLE
BLE

### ISSUE THREAD

**Issue by chrisrosenkreuz23** [lolouk44/hassio-addons#55]
This only seems to use Bluetooth controllers directly connected to the machine running the HA server.
Can it be set up to use the Xiaomi Gateway to read the Bluetooth data coming from the scales? I mean it's even physically connected to the HA server but for some reason there doesn't seem to be any way of making it choose the Gateway as the default bluetooth controller so it can't read the data from the scales. Feel like a schmuck buying into their ecosystem thinking it would be less work setting it all up, only to find out there's no actual way of reading the scales data via their bluetooth controller...

**Comment by lolouk44** [comment]
I'm not sure I understand what you're asking. The add-on uses Bluetooth to connect directly to the scale and extract scale data, so it does not rely on an Internet or cloud connection. It does not connect to any gateway...

**Comment by chrisrosenkreuz23** [comment]
Yes I know that's what I'm saying. So if I can't make the Xiaomi gateway
the default local controller, I won't be able to use the add-on. My
question was whether you were aware of a way to do that. It was a long
shot, figured I'd ask

**Comment by lolouk44** [comment]
sorry I have no idea how to do this.
Stupid questio: why can't you connect to the scale via bluetooth?

**Comment by chrisrosenkreuz23** [comment]
Because I don't have an esp board for the bt. My HA server is a laptop with
a deprecated  Bluetooth version in its onboard controller. I knew this so I
bought a Xiaomi gateway to get the signal from the scales which it does but
in a different app - mi fit (which is the reason the scales don't pop up in
the mi io integration by default). I tried the bluetoothctl command to set
the default controller but it doesn't see the gateway even though it's
physically connected to the laptop. I tried asking around on the discord
server but the big boys told me it can't be done. And I believed them too,
but I just had one more try left in me, heh.

**Comment by lolouk44** [comment]
> My HA server is a laptop with a deprecated Bluetooth version in its onboard controller

See if you can try a Bluetooth dongle? I dont have Bluetooth on my server so that's how I developped this add-on. If not, let me know if you're ok to close this issue...

**Comment by chrisrosenkreuz23** [comment]
Thank you, I will try. Yes ok to close, cheers for your work.
