### ISSUE TITLE
0.2.7 manifest not found: manifest unknown

### ISSUE THREAD

**Issue by IvanUA** [lolouk44/hassio-addons#57]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x ] Xiaomi Mi Scale

**Describe the bug**
On update/install getting an error: Can't install lolouk44/xiaomi-mi-scale-ha-add-on:0.2.7: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.2.7&fromImage=lolouk44%2Fxiaomi-mi-scale-ha-add-on: Not Found ("manifest for lolouk44/xiaomi-mi-scale-ha-add-on:0.2.7 not found: manifest unknown: manifest unknown")

**Comment by lolouk44** [comment]
Sorry about the issues, should be fixed now. Re-open if not
