### ISSUE TITLE
Unable to remove user entity

### ISSUE THREAD

**Issue by raidnet-ms** [lolouk44/hassio-addons#58]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Describe the bug**
I pasted the demo settings into the yaml. Later I deleted the demo users, unfortunately I'm unable to get rid of them as they still appear as entities and they cannot be deleted.

**To Reproduce**
When I click on them I get this message:
This entity ("sensor.mary_weight") does not have a unique ID, therefore its settings cannot be managed from the user interface. See documentation for more details.

**Expected behaviour**
Wish I was able to delete unnecessary users

**Screenshots**
[screenshots .](https://ibb.co/zQ4LQGt)

**Scale (please complete the following information):**
 - Name miscale 2 body composition
 - Model XMTZC05HM

**Device running Home Assistant (please complete the following information):**
 - Device used to run the Script/Container [Raspberry Pi, on HA OS]
 - Bluetooth device used [ Built-in]

**Additional context**

**Comment by lolouk44** [comment]
Toy need to post an empty message to the topic you want to delete with the retain flag set to true. Alternatively you can use an application like MQTT Explorer to delete the unwanted topics

**Comment by raidnet-ms** [comment]
awe I'm not a fan of mqtt :-(
I've tryed to instal mqtt explorer once, without success.
:-D
I think I will stay with timmy and sally for a long time...

**Comment by lolouk44** [comment]
Closing since I've provided a solution

**Comment by raidnet-ms** [comment]
Well thanks anyway, I provided you a feedback 😌
