### ISSUE TITLE
MQTT discovery issue?

### ISSUE THREAD

**Issue by btehan** [lolouk44/hassio-addons#65]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Describe the bug**
I am running HAOS in a VM and have installed Xiaomi Mi Scale v0.3.3 as an add-on.  Here's my config:

>HCI_DEV: hci0
>BLUEPY_PASSIVE_SCAN: false
>MISCALE_MAC: xx:xx:xx:xx:xx:xx
>MISCALE_VERSION: 1
>MQTT_PREFIX: miscale
>MQTT_HOST: 192.168.4.19
>MQTT_USERNAME: username
>MQTT_PASSWORD: password
>MQTT_PORT: 1883
>MQTT_RETAIN: true
>MQTT_DISCOVERY: true
>MQTT_DISCOVERY_PREFIX: homeassistant
>MQTT_TLS_CACERTS: Path to CA Cert File
>MQTT_TLS_INSECURE: true
>TIME_INTERVAL: 30
>USERS:
>  - NAME: Brian
>    SEX: male
>    GT: 160
>    LT: 200
>    HEIGHT: 180
>    DOB: "year-month-day"

The add-on starts and the logs after I weigh myself look good:

>-------------------------------------
>2022-10-04 14:54:31 - Starting Xiaomi mi Scale...
>2022-10-04 14:54:31 - Loading Config From Add-On Options...
>2022-10-04 14:54:31 - Config Loaded...
>-------------------------------------
>2022-10-04 14:54:31 - Initialization Completed, Waiting for Scale...
>2022-10-04 14:54:39 - Publishing data to topic miscale/Brian/weight: {"weight":173.30,"weight_unit":"lbs","bmi":24.26,"basal_metabolism":1551.53,"visceral_fat":14.32,"timestamp":"2022-10-04T14:54:39+00:00"}
>2022-10-04 14:54:39 - Data Published ...
>2022-10-04 14:54:51 - Publishing data to topic miscale/Brian/weight: {"weight":168.50,"weight_unit":"lbs","bmi":23.59,"basal_metabolism":1519.01,"visceral_fat":13.24,"timestamp":"2022-10-04T14:54:51+00:00"}
>2022-10-04 14:54:51 - Data Published ...
>2022-10-04 14:55:01 - Publishing data to topic miscale/Brian/weight: {"weight":173.00,"weight_unit":"lbs","bmi":24.22,"basal_metabolism":1549.44,"visceral_fat":14.25,"timestamp":"2022-10-04T14:55:01+00:00"}
>2022-10-04 14:55:01 - Data Published ...

I am able to see the data in my MQTT broker (EMQX) when I go to Configuration >> MQTT >> Retainer >> miscale/Brian/weight >> Show Payload:

>{
>  "weight": 173,
>  "weight_unit": "lbs",
>  "bmi": 24.22,
>  "basal_metabolism": 1549.44,
>  "visceral_fat": 14.25,
>  "timestamp": "2022-10-04T14:55:01+00:00"
>}

Using MQTT explorer connected to the broker, I am able to see the same three entries as the add-on logs:

>{"weight":173.00,"weight_unit":"lbs","bmi":24.22,"basal_metabolism":1549.44,"visceral_fat":14.25,"timestamp":"2022-10-04T14:55:01+00:00"}
>{"weight":168.50,"weight_unit":"lbs","bmi":23.59,"basal_metabolism":1519.01,"visceral_fat":13.24,"timestamp":"2022-10-04T14:54:51+00:00"}
>{"weight":173.30,"weight_unit":"lbs","bmi":24.26,"basal_metabolism":1551.53,"visceral_fat":14.32,"timestamp":"2022-10-04T14:54:39+00:00"}

However, what I'm not seeing are weight sensors in HA via MQTT discovery.  I always struggle with MQTT, so I feel that this is a config issue on my end, but I could use a hand in figuring this out, please.  

**To Reproduce**
Install the add-on, point it at MQTT broker, weigh yourself.

**Expected behaviour**
[From the docs](https://github.com/lolouk44/hassio-addons/blob/master/mi-scale/DOCS.md#home-assistant-setup), I had expected an entity in HAOS for my weight.  I'm not seeing any when I go to HAOS >> Developer Tools >> States and look for any of the above info.

**Scale (please complete the following information):**
 - xiaomi
 - 1st gen

**Device running Home Assistant (please complete the following information):**
 - HAOS VM on proxmox 7.2
 - USB Dongle

**Comment by radek-kafka** [comment]
I can the same.. the function for MQTT_Discovery is not called so new sensors after adding/changing of new user is not called.. I do not see any messages adding of sensor to be published in mqtt ..

**Comment by lolouk44** [comment]
Thanks for bringing this up. Fixed in [0.3.4](https://github.com/lolouk44/hassio-addons/releases/tag/0.3.4) which should be built in 10-15 min

**Comment by twangraus** [comment]
@lolouk44 is the BLUEPY_PASSIVE_SCAN option still relevant, as the bluepy is no longer supported?

**Comment by lolouk44** [comment]
@btehan @radek-kafka can you confirm MQTT Discovery is working and close this issue if applicable?

**Comment by radek-kafka** [comment]
> @btehan @radek-kafka can you confirm MQTT Discovery is working and close this issue if applicable?

I did re-install .. Readme is version 0.3.4 but the code is the old one 0.3.3 .. Also version shown is still 0.3.3.. Shall be patient and wait till image is ready .. :) Many thanks

**Comment by lolouk44** [comment]
Code in 0.3.4 is defo updated. You may need to reboot your HA instance to it can catch up with the update

**Comment by btehan** [comment]
0.3.4 fixed this.  Thank you @lolouk44  :⁠-⁠)

**Comment by radek-kafka** [comment]
Shall be ok:) Thx .. 
022-10-05 13:56:53 - Starting Xiaomi mi Scale...
2022-10-05 13:56:53 - Loading Config From Add-On Options...
2022-10-05 13:56:53 - Config Loaded...
2022-10-05 13:56:53 - MQTT Discovery Setup Completed...
-------------------------------------
2022-10-05 13:56:53 - Initialization Completed, Waiting for Scale...

**Comment by RestOp** [comment]
I have this problem till now, version 0.3.6
No sensors are created...
