### ISSUE TITLE
Config Page fills optional Parameters with defaults

### ISSUE THREAD

**Issue by stefangries** [lolouk44/hassio-addons#7]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [X] Xiaomi Mi Scale

**Describe the bug**
When removing a parameter like "USER3_SEX" and clicking "save", the parameter reappears when reentering the config page. The parameter gets filled with its default.

**Expected behaviour**
The optional parameter should be removeable instead of readding it with its default value.

**Comment by lolouk44** [comment]
Thanks I've experienced the same. I think it's a défaite behaviour from home assistant that auto fills back with défaite data from config.json
I could remove all prefilled data but then songs of the fields aren't obvious if they need to be enclosed in quotes or not so for now I had left it like that...

**Comment by stefangries** [comment]
I **think**, the optional parameters should not be named in the "options" object in config.json.

**Comment by lolouk44** [comment]
Probably not. I'll try and remove the optional stuff to see how it looks in the gui then I'll update here

**Comment by lolouk44** [comment]
So I've had a look at the [doc](https://developers.home-assistant.io/docs/add-ons/configuration/#options--schema) and experimented a bit.
I cannot provide an option without a default value.
I could replace the default values with a blank `""` but that's not really an answer. If you remove entries in the config, they will still show up with empty strings...
Thoughts?

**Comment by stefangries** [comment]
To be honest, I don't know how to solve it then. It's not so bad, though.

But in the documentation the role of USER3 should be described better. In any case, it is not clear to me when a measured value is assigned to USER3.

For example, I have USER1_GT=79 and USER2_LT=78, but there are no such options for USER3. So I don't understand at all when USER3 is selected for a measured value. That's why I needed to remove USER3 from the config completely.

**Comment by lolouk44** [comment]
ok, I'll update the readme.
Basically, if measured value is greater than USER1_GT, then it gets assigned to USER1
Else if measured value is less than USER2_LT, then it gets assigned to USER2
Else it gets assigned to USER3

**Comment by stefangries** [comment]
Ah, okay. So USER3 is selected if weight < USER1_GT and weight > USER2_LT?

**Comment by lolouk44** [comment]
you got it 😄

**Comment by stefangries** [comment]
Ah okay, thanks 😊
