### ISSUE TITLE
Add-on not recognized as valid repository on Home Assistant

### ISSUE THREAD

**Issue by luisfsr** [lolouk44/hassio-addons#71]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x ] Xiaomi Mi Scale

**Describe the bug**
When you open Home Assistant and navigate to the "Add-on Store" and click on the 3 dots (top right) and select "Repositories", and then enter https://github.com/lolouk44/hassio-addons in the box and finally click on "Add", Home Assistant warns that the add-on is not a valid repository.
![xiaha](https://user-images.githubusercontent.com/18434789/199992631-cc73c034-5192-4aa3-8a13-6c71df1fe3ec.png)

**Comment by lolouk44** [comment]
Please fill in **ALL** requested fields / questions when creating a bug.

**Comment by lolouk44** [comment]
By the way you're missing an '`s`' after http in the url.
