### ISSUE TITLE
Add support ESPHome BLE active adapter

### ISSUE THREAD

**Issue by fantnhu** [lolouk44/hassio-addons#72]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Is your feature request related to a problem? Please describe.**
Hi!
I have a problem and I couldn't find any information about it. I have an XMTZC02HM scale and an ESPHome BLE (active) bluetooth connection.
I would like to set this adapter in the integration, but unfortunately I can't do it.
Does it only work with a physically connected adapter? Or in what format should I enter the path?

Thank you in advance for your answer!

**Comment by laurentmahe** [comment]
Hi,

The add-on only works with physical Bluetooth Adapters.
If you want to use an ESP device, try https://www.esphome.io/components/sensor/xiaomi_miscale.html

**Comment by lolouk44** [comment]
Hi,

The add-on only works with physical Bluetooth Adapters.
If you want to use an ESP device, try https://www.esphome.io/components/sensor/xiaomi_miscale.html
