### ISSUE TITLE
LOG Level doesnt exist

### ISSUE THREAD

**Issue by clipse2004** [lolouk44/hassio-addons#74]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [ x] Xiaomi Mi Scale

**Describe the bug**
Addons works Perfect, but there is always an Error Message in the Log:

22-12-29 23:30:58 WARNING (MainThread) [supervisor.addons.options] Option 'LOG_LEVEL' does not exist in the schema for Xiaomi Mi Scale (79ff755f_xiaomi_mi_scale)

**Device running Home Assistant (please complete the following information):**
 - Device used to run the Script/Container [e.g. Raspberry Pi, NUC]
 - Bluetooth device used [e.g. Built-in, USB Dongle]
 - Built in and external

**Home Assistant Version:**

2022.12.8

**Additional context**
As said the addon works, the LOG mode info is also set.
No matter what I try, the warning keeps popping up in the LOG.

**Comment by lolouk44** [comment]
Can you share your config please? It sounds like you have set an incorrect option for the logging level

**Comment by lolouk44** [comment]
Let me know if this is still an issue or if it can be closed

**Comment by clipse2004** [comment]
Sorry i forgot to write, the Error still exist.
Here is my config:

HCI_DEV: hci1
BLUEPY_PASSIVE_SCAN: true
MISCALE_MAC: D0:3E:7D:A2:D5:A0
MQTT_PREFIX: miscale
MQTT_HOST: a0d7b954-emqx
MQTT_USERNAME: hassio_mqtt
MQTT_PASSWORD: "!secret mqtt_pass"
MQTT_PORT: 1883
MQTT_RETAIN: true
MQTT_DISCOVERY: true
MQTT_DISCOVERY_PREFIX: homeassistant
MQTT_TLS_CACERTS: Path to CA Cert File
MQTT_TLS_INSECURE: false
DEBUG_LEVEL: error
USERS:
  - NAME: Marco
    SEX: male
    GT: 70
    LT: 120
    HEIGHT: 183
    DOB: "1985-10-27"
  - NAME: Marion
    SEX: female
    GT: 40
    LT: 70
    HEIGHT: 170
    DOB: "1989-04-24"
LOG_LEVEL: info

**Comment by lolouk44** [comment]
> * LOG_LEVEL: info

This is your issue, it should not be there

**Comment by lolouk44** [comment]
stale
