### ISSUE TITLE
MQTT Discovery still do not create sensors

### ISSUE THREAD

**Issue by RestOp** [lolouk44/hassio-addons#77]
Hello,

last version of HA in Docker and 0.3.6 of addon, but still the same issue https://github.com/lolouk44/hassio-addons/issues/65#issuecomment-1385113688

![image](https://user-images.githubusercontent.com/46259141/212866015-d6743603-1b66-4142-8555-1d7f8a089800.png)

![image](https://user-images.githubusercontent.com/46259141/212866125-727fc95a-3dc9-4801-9373-f50e0b2dec69.png)

MQTT is working
![image](https://user-images.githubusercontent.com/46259141/212866217-1c4b1b53-2946-4c6b-92a1-283df18cafb4.png)

Thanks a lot!

**Comment by lolouk44** [comment]
Can you show your MQTT data for /homeassistant to ensure the miscale data sensor is there too?
Do you have anything in the HA logs regarding MQTT discovery at startup?

**Comment by RestOp** [comment]
Thanks for reply!
Here is the MQTT data from MQTT.fx
![image](https://user-images.githubusercontent.com/46259141/212876365-382351d7-e8a6-4096-b9cb-04a5c87b82dd.png)
No the logs are empy, it seems that everything ius ok with mqtt

**Comment by RestOp** [comment]
What could you advice me to do?
Thanks!

**Comment by lolouk44** [comment]
Sorry busy with work at the mo and my test Pi has died... Give me some time to look into this.
In the meantime you can manually create the sensors, check the [doc](https://github.com/lolouk44/hassio-addons/blob/master/mi-scale/DOCS.md#home-assistant-setup)

**Comment by lolouk44** [comment]
Can you try to remove the space in your user name? I wonder if it's the culprit.
You could replace it with an underscode, e.g. `Michael_S`

**Comment by RestOp** [comment]
Thanks, it ssems that it has helped! But in my other HA server i have the same config without underscore and it forks fine.
But in all cases now it works!
