### ISSUE TITLE
Getting 2 weight entries and not as much info as in the screenshot (e.g. bone mass etc)

### ISSUE THREAD

**Issue by atv2016** [lolouk44/hassio-addons#78]
So i followed the instructions for adding the MQTT sensors, and i did read the the weight entry gets added automatically (probably why i now have 2) but then why was the weight sensor defined in the example code. Do i need to add it under the sensors: heading or not.

Also, in your screenshot i see lots of other things, i only get Visceral Fat and then the Timestamp attribute for the weight sensor.

**Comment by lolouk44** [comment]
Please provide all the requested information if you need help, I can't really help otherwise

**Comment by atv2016** [comment]
Sure, ok. I used the bug report below, let me know if you need anything else.

**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [ ] Xiaomi Mi Scale

**Describe the bug**
Getting 2 weight sensors + only seeing sub attribute Visceral Fat (up to timestamp) in the weight attribute.

**To Reproduce**
Steps to reproduce the behaviour, including error message if any.
I just added the MQTT code to my mqtt.yaml under sensors:

**Expected behaviour**
A clear and concise description of what you expected to happen.
One weight sensor and inclusion of all the sub attributes as on the main page of the integration.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Scale (please complete the following information):**
 - Name Xiaomi Bodyfat Scale 2
 - Model 2

**Device running Home Assistant (please complete the following information):**
 - Device used to run the Script/Container [e.g. Raspberry Pi, NUC]
 I run HA on Ubuntu, in a VM, and use the add-on for this integration
 - Bluetooth device used [e.g. Built-in, USB Dongle]
USB dongle (long range)

**Home Assistant Version:**
e.g. 2010.01.1
Latest version (non-beta)

**Additional context**
Add any other context about the problem here.

**Comment by atv2016** [comment]
I didn't realise these scales work with bare feet e.g. impedance. Once i did that, i got all the remaining sub attributes.
Thanks! 

Not sure why i still get 2 sensors for weight though..

**Comment by atv2016** [comment]
Also - something i noticed is the first time someone steps on the scale with bare feet, it doesn't seem to record those extended sub attributes.

**Comment by lolouk44** [comment]
This is normal, when you step on the scale, it first reads the weight alone (and the scale broadcasts this), then it reads the body impedance (and broadcasts both weight and impedance) impedance is required for the additional metrics, that's why you only get partial info after the initial broadcast.

**Comment by atv2016** [comment]
Cool, but why am I getting two weight sensors though? I do need the mqtt weight sensor right?
________________________________

**Comment by lolouk44** [comment]
You'd need to delete one of the entries in the home assistant discovery topic (homeassistant by default) on your MQTT broker

**Comment by atv2016** [comment]
Yeah, i'm looking with with mqttexplorer but i only see one topic per user.
Maybe i should just delete it from HA ?
________________________________

**Comment by lolouk44** [comment]
sure you could always delete it from HA. I'm not sure how you've set it up. There are many ways, just depends on what you've done.
Either delete from MQTT if using discovery and/or delete from HA if manually added to config.
