### ISSUE TITLE
Images on Info Page are broken

### ISSUE THREAD

**Issue by stefangries** [lolouk44/hassio-addons#8]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [X] Xiaomi Mi Scale

**Describe the bug**
![image](https://user-images.githubusercontent.com/10342151/86827261-0f240b00-c092-11ea-8cfb-0326ea7c7157.png)

**Comment by lolouk44** [comment]
Thanks. I've also seen this. Images are using full url (not relative) so not sure how to resolve. This is automatically pulled from the repo from HA

**Comment by stefangries** [comment]
Try using different URLs in the Readme like this:

https://raw.githubusercontent.com/lolouk44/xiaomi_mi_scale/master/Screenshots/Mi_Smart_Scale_2_Thumb.png
instead of 
https://github.com/lolouk44/xiaomi_mi_scale/blob/master/Screenshots/Mi_Smart_Scale_2_Thumb.png

It might work, but actually I haven't tried.

**Comment by lolouk44** [comment]
Thanks I'll give it a go tomorrow and report

**Comment by lolouk44** [comment]
it points to an actual picture instead of an HTML page containing the picture so I've changed that in branch 0.1.8
