### ISSUE TITLE
Installation in HA Core (venv)

### ISSUE THREAD

**Issue by Poimander** [lolouk44/hassio-addons#80]
- [x] Xiaomi Mi Scale
Is it possible to install that integration in Home Assistant Core (python virtual environment installation) by copying ./src files into "custom_components" directory? Thanks very much!

**Comment by lolouk44** [comment]
Check my other repo:
https://github.com/lolouk44/xiaomi_mi_scale although it's been a very long time since I ran this directly. I run this through a docker container
