### ISSUE TITLE
Cannot see add-on after adding repository

### ISSUE THREAD

**Issue by H0nzik1** [lolouk44/hassio-addons#84]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [ ] Xiaomi Mi Scale

**Describe the bug**
When I add https://github.com/lolouk44/hassio-addons to repositories, nothing appears. No error when adding repository.

**To Reproduce**
just add https://github.com/lolouk44/hassio-addons to repositories

**Expected behaviour**
to see addon

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/28353840/233839124-831dd00a-a3f4-46db-b26c-9f5d5d4cfcf1.png)
![obrazek](https://user-images.githubusercontent.com/28353840/233839133-bd5150b8-79f4-4b83-87a7-fefc65ca65d7.png)

**Scale (please complete the following information):**
Does not matter now.

**Device running Home Assistant (please complete the following information):**
 - Device used to run the Script/Container [e.g. Raspberry Pi, NUC]
 - Bluetooth device used [e.g. Built-in, USB Dongle]

**Home Assistant Version:**
2023.4.6

**Additional context**
no

**Comment by lolouk44** [comment]
What do the logs show ?

**Comment by H0nzik1** [comment]
> What do the logs show ?

It finaly appeared after updating to 2023.4.6. But I am not sure if it was the cause of the problem.

**Comment by lolouk44** [comment]
Thanks for confirming. Closing issue...
